twig:
    globals:
        deployment_environment: '%env(default:deployment_environment:APP_DEPLOYMENT_ENV)%'
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
        - 'form/fields.html.twig'

when@test:
    twig:
        strict_variables: true
