<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260903143000 extends AbstractMigration
{
    public function getDescription(): string { return 'Adds companies, ERP-scoped connections, and menu permissions.'; }
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE company (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(160) NOT NULL, legal_name VARCHAR(220) DEFAULT NULL, document VARCHAR(24) DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql("INSERT INTO company (name, legal_name, is_active, created_at) VALUES ('Empresa local', 'Empresa local', true, NOW())");
        $this->addSql('ALTER TABLE erp_connection ADD company_id INT DEFAULT NULL');
        $this->addSql('UPDATE erp_connection SET company_id = (SELECT id FROM company ORDER BY id ASC LIMIT 1)');
        $this->addSql('ALTER TABLE erp_connection ALTER company_id SET NOT NULL');
        $this->addSql('DROP INDEX UNIQ_ERP_CONNECTION_NAME');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ERP_CONNECTION_COMPANY_NAME ON erp_connection (company_id, erp_name)');
        $this->addSql('CREATE INDEX IDX_ERP_CONNECTION_COMPANY ON erp_connection (company_id)');
        $this->addSql('ALTER TABLE erp_connection ADD CONSTRAINT FK_ERP_CONNECTION_COMPANY FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE company_membership (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, company_id INT NOT NULL, user_id INT NOT NULL, erp_identifier VARCHAR(160) DEFAULT NULL, erp_display_name VARCHAR(220) DEFAULT NULL, erp_email VARCHAR(180) DEFAULT NULL, menu_permissions JSON NOT NULL DEFAULT '[]', is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_COMPANY_MEMBERSHIP ON company_membership (company_id, user_id)');
        $this->addSql('CREATE INDEX IDX_COMPANY_MEMBERSHIP_USER ON company_membership (user_id)');
        $this->addSql('ALTER TABLE company_membership ADD CONSTRAINT FK_COMPANY_MEMBERSHIP_COMPANY FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_membership ADD CONSTRAINT FK_COMPANY_MEMBERSHIP_USER FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("INSERT INTO company_membership (company_id, user_id, menu_permissions, is_active, created_at) SELECT (SELECT id FROM company ORDER BY id ASC LIMIT 1), id, '[\"dashboard\",\"products\",\"clients\",\"suppliers\",\"carriers\",\"requisition\",\"approval\",\"connections\"]', true, NOW() FROM app_user WHERE LOWER(username) = 'kadmin' ON CONFLICT (company_id, user_id) DO NOTHING");
    }
    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE erp_connection DROP CONSTRAINT FK_ERP_CONNECTION_COMPANY');
        $this->addSql('DROP INDEX UNIQ_ERP_CONNECTION_COMPANY_NAME');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ERP_CONNECTION_NAME ON erp_connection (erp_name)');
        $this->addSql('ALTER TABLE erp_connection DROP company_id');
        $this->addSql('DROP TABLE company_membership');
        $this->addSql('DROP TABLE company');
    }
}
