<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260902133000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adds masked ERP WebService execution logs.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE erp_connection_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, connection_id INT DEFAULT NULL, service_name VARCHAR(160) NOT NULL, port_name VARCHAR(120) DEFAULT NULL, endpoint VARCHAR(500) NOT NULL, method_name VARCHAR(80) NOT NULL, payload_masked JSON NOT NULL DEFAULT '{}', response_received TEXT DEFAULT NULL, status_http SMALLINT DEFAULT NULL, success BOOLEAN NOT NULL, error_code VARCHAR(80) DEFAULT NULL, error_message TEXT DEFAULT NULL, response_time_ms INT NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))");
        $this->addSql('CREATE INDEX IDX_ERP_LOG_CONNECTION_DATE ON erp_connection_log (connection_id, created_at)');
        $this->addSql('ALTER TABLE erp_connection_log ADD CONSTRAINT FK_ERP_LOG_CONNECTION FOREIGN KEY (connection_id) REFERENCES erp_connection (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE erp_connection_log');
    }
}
