<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260901153000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adds the active ERP selection used by KFlow360.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE erp_connection (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, erp_name VARCHAR(64) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ERP_CONNECTION_NAME ON erp_connection (erp_name)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE erp_connection');
    }
}
